---
title: Andrew.
copyright: ©2010-2016 Marc Andrew Harter

baseURL: https://wavded.com
disableHugoGeneratorInject: True
pygmentsCodeFences: True
pygmentsStyle: manni
footnoteReturnLinkContents: "↩"
