---
title: Andrew.
copyright: ©2010-2016 Marc Andrew Harter

baseURL: http://wavded.com
buildDrafts: True
disableHugoGeneratorInject: True
pygmentsCodeFences: True
pygmentsStyle: manni
footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"

params:
  githubURL: https://github.com/wavded/www
